services:
  xkeen-ui-controller:
    image: vchikalkin/xkeen-ui-controller:latest
    ports:
      - '3000:3000'
    environment:
      DATA_DIR: /data
      MIHOMO_CONFIG_PATH: /opt/etc/mihomo/config.yaml
      XKEEN_UI_PORT: '1000'
    volumes:
      - /config/xkeen-ui-controller:/data
    restart: unless-stopped
